version: "3.9"
services:
  api:
    container_name: blog-api
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - target=dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      BLOG_ENV: dev
      BLOG_APP_PORT: 3000
      BLOG_AWS_S3_BUCKET: ${BLOG_AWS_S3_BUCKET:?err}
      BLOG_AWS_S3_THUMBNAIL_DIRECTORY: ${BLOG_AWS_S3_THUMBNAIL_DIRECTORY:?err}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:?err}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:?err}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:?err}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      BLOG_KVS_HOST: blog-kvs
      BLOG_KVS_PORT: 6379
      BLOG_KVS_USER: default
      BLOG_KVS_PASSWORD: redispw
      BLOG_DB_HOST: blog-rdb
      BLOG_DB_PORT: 3306
      BLOG_DB_USER: blog_user
      BLOG_DB_PASS: blog
      BLOG_DB_NAME: blog

  blog-rdb:
    image: mysql:latest
    container_name: blog-rdb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: blog_user
      MYSQL_PASSWORD: blog
      MYSQL_DATABASE: blog
    volumes:
      - blog-rdb-data:/var/lib/mysql

  blog-kvs:
    image: redis:latest
    container_name: blog-redis
    ports:
      - "6379:6379"
    volumes:
      - blog-redis-data:/data

volumes:
  blog-rdb-data:
  blog-redis-data:
