version: "3.9"
services:
  api:
    container_name: blog-api
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - target=dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      BLOG_ENV: dev
      BLOG_APP_PORT: 3000
      BLOG_AWS_S3_BUCKET: ${BLOG_AWS_S3_BUCKET:?err}
      BLOG_AWS_S3_THUMBNAIL_DIRECTORY: ${BLOG_AWS_S3_THUMBNAIL_DIRECTORY:?err}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:?err}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:?err}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:?err}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      BLOG_KVS_HOST: blog-kvs
      BLOG_KVS_PORT: 6379
      BLOG_KVS_USER: default
      BLOG_KVS_PASSWORD: redispw

  blog-kvs:
    image: redis:latest
    container_name: blog-redis
    ports:
      - "6379:6379"
    volumes:
      - blog-redis-data:/data
volumes:
  blog-redis-data:
