openapi: "3.0.0"
info:
  title: Blog backend API
  version: "1.0"

paths:
  /blogs:
    get:
      summary: ブログの一覧
      parameters:
        - name: keyword
          in: query
          description: 検索キーワード
          required: false
          schema:
            type: string
        - name: tag
          in: query
          description: 検索タグ
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Blog"

    post:
      summary: ブログの投稿
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BlogRequestBody"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Blog"

  /blogs/{blog_id}:
    get:
      summary: ブログの取得
      description: ブログを1件取得する
      parameters:
        - name: blog_id
          in: path
          description: ブログID
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Blog"

    delete:
      summary: ブログの削除
      description: ブログを1件削除する
      parameters:
        - name: blog_id
          in: path
          description: ブログID
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BlogId"
                  
    put:
      summary: ブログの更新
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Blog"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Blog"
components:
  schemas:
    BlogId:
      type: object
      properties:
        id:
          type: integer
          description: ブログID
          example: 1

    BlogRequestBody:
      allOf:
        - $ref: "#/components/schemas/BlogDomain"

    BlogDomain:
      type: object
      properties:
        title:
          type: string
          description: タイトル
          example: XXXについてまとめました
        description:
          type: string
          description: 概要
          example: 知見共有のためXXXについてまとめました。
        content:
          type: string
          description: 本文
        authorId:
          type: integer
          description: 投稿者
          example: 1
        thumbnailImageFileName:
          type: string
          description: サムネイル画像ファイル名
        isPublic:
          type: boolean
          description: 公開/非公開
        tags:
          type: array
          items:
            type: string

    Blog:
      allOf:
      - type: object
        properties:
          id:
            type: integer
            description: ブログID
            example: 1
      - $ref: "#/components/schemas/BlogDomain"
      - $ref: "#/components/schemas/CommonColumn"
        
    CommonColumn:
      type: object
      properties:
        created:
          type: string
          description: 作成日
          format: date-time
          example: "2023-12-31T09:10:58+09:00"
        updated:
          type: string
          description: 更新日
          format: date-time
          example: "2023-12-31T09:10:58+09:00"